travis:
  secure:
    BINSTAR_TOKEN: p9d2/xZBxSZGLY/TmoJcpkeQWYdHjs9GPEcpznH/tmCUvDgzCxazs/y+hA1Ey7nv6uC+7Z40qNCkRNMYbKxr9htFJ3qjuCN2Rq7WNMXFcAhe9MzZmqg8sQnf8QQ9QXppwxBAnmeM9GWtLtLYJDWqxQH3moHsK/tSdBAG9Rus3/SbIrWbmDJJozR8cD6BL5h0FFUG1TkQM261ZAgDMbqReMT5dx2ZgbToJwbMAmPcSDq0Ej6DbtBmSc7B71Y4gml2ykB4IchA5cGho+DBBavv5WgLKzG9tVeLu5iKqQCy6kStwl+oBdVawrEIPH/Pb9e4OEgu3fX+LVEw03BtQPiaAvAqsrhweULffUHE6FJaRJwBfS7s4afiW3tGD8Nglvn5TObgilQVUrPKkD8iqHFlnNXvSZXcVayum3jxplB93MmKPM1tnlwdJAz773JPeBU7TCQgi3PNoi6VYqRjLkglda6lWqBDh4RF4fZvLPilYGnJ2pns3XKbO6jXmF6ZYDXkkbYOMpuW2pNucHIEEA80lqm4yyKPe+LZsFZ/Z+213aBVKeQeotroLP8O7DK8X/ruu74vK/Hw1orjhQcnisz3xrmYyan8izPnrCY3xgLMc0u5KF6bftmzQAsSf79rH72hJOeHuz0EC43Mnc+MHAuQnCg5XvuGbjegPb0c0Sl6TpY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
