travis:
  secure:
    BINSTAR_TOKEN: ApRSxexnokJqniDb+sInmF4bRGcj6ZhSBw7F+YpUwnBxlUZycEjPIEUkHcP0DK8LnC1k9D+CM/+UdOhCqhQ0nWoR2tgiPoeeSRQ6r/T324uPJlt8HK4SscU6eWLfpx0mtCdFaDY76BQRcr1jDGrG613hr6aGHrrAeod7wNRYztlVbQStpDMot2O/5oqOR2tCljATDMORJGdps9yTWeetKuHjhhMXBsE5xxFxKITyc8kmP5/CZfLVZJmKmB91AFwJ5qg0caTOfywCKJNdnUG/Cw4V8TVPWrTlrIjGmgSunsK4Gk113ycfFqGiWxv+7Z1TCAW3V0egijkl5Ou9cx+qHpuCD+P58MeOppiVy1TpfaFE3vWcLCvSALuEbaNfSc0yP8kAaiXMdad9O19VscRE7b2uI9My7WmTtjYDgvSHh2tThrExyxPmwaWMG7jMI90avKMejayRjGx93boPQ6NawgVsMYOF13CxzS02xfSJIT6WQu4vu6N6XBdpRbZaRQwDIEUbn94Ye/ERitFaejCVLs4wAGngrOwJryS9KxNn9wQyCP6eYpKTQudvZiaoRQR+myZ/WJYzn5y5GBH8MZdJD9o2ZNsrer2gbcQcIK6CzLIOgYgAXRHUVfF65y7app4aXzMqaxVGgo79kcaD4i4U74buOkdFgCG40qk9pUO74Oc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
